### PR TITLE
Support adding extra tags to new stacks

### PR DESCRIPTION
**Pull request by jmcs**

### CODE REVIEW

**Comment by hjacobs** [comment]
Why do we need this? This looks like a special code path just to add tags --- it could also be achieved via the Senza definitional YAML + custom parameters.

**Comment by jmcs** [comment]
I need it for lizzy. I want to tag the stacks without having to change the yaml file provided in the request.

**Comment by hjacobs** [comment]
@jmcs OK, could you add a test for the added code? I'm not sure why the code coverage is not shown here in the PR... Thanks!

**Comment by jmcs** [comment]
@hjacobs done

**Pull request merged**
