### PR TITLE
Show error when stack is not found

### LINKED ISSUE #263: Does not show error when stack does not exist
When I call:

```
$ senza delete this.stack.does.not.exists v33 --region eu-central-1
```

Senza does not show me an error that the stack does not exist neither returns 1. So if I have a typo in the name nothing happens at all leaving me without clue of what is happening.

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Fixes #263

### CODE REVIEW

**Comment by jmcs** [comment]
Can you add an option to ignore if the stack doesn't exist (`-f` would be ideal to mirror `rm` but it's already taken :( )?

**Comment by rafaelcaricio** [comment]
@jmcs in this case the error is only shown when there is not found stacks at all. So even without option if there is more than one stack to delete, it will ignore.

**Comment by jmcs** [comment]
There can be situations (specially on CI\CD jobs) where I don't care if the stack exists or not, I just want to make sure it doesn't exist after I run the command.

**Comment by rafaelcaricio** [comment]
@jmcs done!

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
