### PR TITLE
Target health check

### LINKED ISSUE #286: Consider enabling "Evaluate Target Health" for Alias DNS records
To get a nice DNS failover (only direct traffic to stacks with healthy ELB).

### PR DESCRIPTION
**Pull request by jmcs**
Fixes #286 

Note: I still didn't test this changes with real stacks

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
👍

**Comment by hjacobs** [comment]
I would not make this the default --- having this always on might lead to undesirable behavior (DNS lookup failure instead of "Service Temporarily Not Available").

I would leave it to the user whether he wants DNS failover (which requires having at least one other stack deployed).

We should also test the actual AWS behavior (how does it behave if the other stack has weight zero etc?).

**Comment by hjacobs** [comment]
Hmm, actually we delete DNS records with weight zero, so DNS failover would not work out-of-the-box with one "primary" (weight 200) and one "secondary" (weight 0) stack.

**Comment by jmcs** [comment]
I'm going to close the PR until I can do some tests.

**Pull request closed without merging**
