### PR TITLE
Fix #296 include spot price field for launch configuration

### LINKED ISSUE #296: Senza ignores "SpotPrice" property on auto scaling group
```
      InstanceType: m4.xlarge
      SpotPrice: 0.250
```

According to cloudformation specs this will create an ASG with spot instances.

### PR DESCRIPTION
**Pull request by Jan-M**

### CODE REVIEW

**Comment by Jan-M** [comment]
Fix #296

**Comment by hjacobs** [comment]
Can you add a test please?

**Comment by Jan-M** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
