### PR TITLE
Adding the 'TargetGroup' for ALB inside the loop

### PR DESCRIPTION
**Pull request by duergner**
When using an `ElasticLoadBalancerV2` the `TargetGroup` name was not appended on the actual ref but rather tried to be added to the list itself which causes a Python error to be thrown.

Looked like a copy and past error from the `ElasticLoadBalancer` version.

### CODE REVIEW

**Comment by hjacobs** [comment]
I'm wondering how this could have worked before?

**Comment by hjacobs** [comment]
Can you add a test for this case?

**Comment by duergner** [comment]
Sure - will push tomorrow morning.

The syntax for the old ELB version is slightly different as there's been no need to append the `TargetGroup` suffix. I assume it never worked for ALBs

**Comment by duergner** [comment]
I added test cases for both `ElasticLoadBalancer` and `ElasticLoadBalancerV2` references for the three different cases each I believe should provide full coverage

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
I'm fixing the tests (rely on date :disappointed: )

**Comment by hjacobs** [comment]
@duergner I fixed the tests in #462, please rebase your PR..

**Comment by duergner** [comment]
@hjacobs done

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Released: https://github.com/zalando-stups/senza/releases/tag/2.1.70

**Pull request merged**
