### PR TITLE
Implement redis node and redis cache cluster components and templates

### PR DESCRIPTION
**Pull request by marek-obuchowicz**
Added some functionality for data layer: Elasticache redis. Supports both single-node setup (suitable for caching, where data loss can occur, without replication) and multiple-node setup (with replication group and automatic failover enabled).

### CODE REVIEW

**Comment by hjacobs** [comment]
Hi @marek-obuchowicz, thanks for the PR --- could you fix the Travis CI build (e.g. flake8 code formatting), please?

**Comment by marek-obuchowicz** [comment]
Thanks for the hint, code formatting has been fixed. One test (not related to this PR) still fails.

**Comment by hjacobs** [comment]
@marek-obuchowicz could you check the failing test please? it must be related to the PR "somehow"..

**Comment by marek-obuchowicz** [comment]
Fixed failing test for this case, IMO it smells as it relies on order of displayed templates, not on the names (order changes whenever we add/remove templates). Coverage decreased as we don't test templates at all.

**Pull request merged**
