### PR TITLE
Support for additional properties, eg. IdleTimeout of load balancer

### PR DESCRIPTION
**Pull request by grzegorzjeziorski**
I added one additional line for supporting http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes in ELBv2

### CODE REVIEW

**Comment by hjacobs** [comment]
Did you test with the empty `{}`?

**Comment by grzegorzjeziorski** [comment]
Should be fixed now. I tested both variants, with and without a property set.

**Comment by hjacobs** [comment]
:+1:

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
