### PR TITLE
Fix testing pipeline

### PR DESCRIPTION
**Pull request by hughcapet**
- CDP overlays -> runtime
- Remove top-level region option
- Define a separate Command class for flake8 in setup.py (flake8 setuptools/setup.py support is now deprecated)
- Fix a flake8 error

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by jmcs** [comment]
LGTM but I've a question. Why are you removing the top-level region option?

**Comment by hughcapet** [comment]
@jmcs 

sorry, should have posted the message from one of the commits. This is because this was causing the following misbehavior (revealed in the `test_cli.py` unit tests):
```
The current implementation uses value set via the envvar AWS_DEFAULT_REGION
for sub-commands even if an explicit flag value is provided.
```

And I actually don't fully understand the whole idea of having the top-level region option.

**Comment by hughcapet** [comment]
👍

**Pull request merged**
