### PR TITLE
Show helpful error if dns.resolver import fails

### PR DESCRIPTION
**Pull request by jmcs**
I'm singling out this import since it's the only import error I saw on Sentry and there are already multiple reports from multiple hosts.

### CODE REVIEW

**Comment by hjacobs** [comment]
@jmcs the message should mention the "--force-reinstall" --- the problem is that "dnspython" IS installed but with empty module directory (they changed from dnspython3 to dnspython package IIRC).

**Comment by jmcs** [comment]
@hjacobs thanks. What message do you suggest? "Run (sudo) pip3 install --upgrade ---force-reinstall dnspython"?

**Comment by rafaelcaricio** [comment]
@jmcs please no `sudo`.

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
