### PR TITLE
Exporting ApplicationName as an AWS tag for ELBs

### PR DESCRIPTION
**Pull request by jkozlowicz**
I added a way to export `ApplicationName` attribute in `SenzaInfo` section as an AWS tag for the ELB.

More info: #451

### CODE REVIEW

**Comment by hjacobs** [comment]
That code looks tailored to a very specific use case. Why was `StackName` not good enough?

**Comment by hjacobs** [comment]
Or why not add Tags in your Senza def directly (not requiring Senza code changes)?

**Comment by jkozlowicz** [comment]
`StackName` was not enough because it can vary across AWS accounts of different teams - `LizzyAgent` has its `StackName` set to `lizzy-<team_name>`.

We need a unified way to target all ELBs of `LizzyAgents` in `ZMON`. This way we can target all entities with `application_name` equal to `X`.

I was not aware that tags could be added in senza definition in a way that then they can be used to filter entities in `ZMON`.

**Comment by hjacobs** [comment]
I think the PR makes no sense as it is now (too specific). We should try to add the option to add Tags to the ALB (if this does not work yet?).

**Comment by jkozlowicz** [comment]
@hjacobs yes you are right. We were able to add tags to ALB in senza definition for `Lizzy` so this one can be closed.

**Comment by hjacobs** [comment]
@jkozlowicz cool, thanks.

**Pull request closed without merging**
