### PR TITLE
Fix issue with changed set traffic handling

### PR DESCRIPTION
**Pull request by duergner**
The PR which introduced the changed handling of set traffic solving the UPDATE_IN_PROGRESS issue with stacks having multiple ELBs (and therefore multiple DNS names) did treat a `stack` object returned by `CloudFormationStack.get_by_stack_name` as if it would be the same object being returned by subsequent calls with the same stack_name. As this is not the case this leads to only the first update being actually executed.

### CODE REVIEW

**Comment by jmcs** [comment]
Can you include some tests for this?

**Comment by duergner** [comment]
I can do so yes - any chance to merge that PR and have the tests on a follow up PR?

**Comment by jmcs** [comment]
:+1:

**Comment by duergner** [comment]
@jmcs @hjacobs any chance this PR could get merged and released?

**Comment by jmcs** [comment]
:+1:

**Comment by last-ent** [comment]
👍

**Pull request merged**
