### PR TITLE
Disable InstanceMonitoring for LaunchConfiguration if needed

### PR DESCRIPTION
**Pull request by mnatsakanyank**
There should be a way to disable InstanceMonitoring if its not needed for LaunchConfiguration

### CODE REVIEW

**Comment by mnatsakanyank** [comment]
@hjacobs @jmcs Guys can you please take a look on this pull request, this will allow us to reduce costs  by 30%. Thanks.

**Comment by jmcs** [comment]
:+1:

**Comment by hjacobs** [comment]
For reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-instancemonitoring

**Comment by hjacobs** [comment]
:+1:

**Comment by mnatsakanyank** [comment]
@hjacobs @jmcs Thanks for approval. Do you maybe know an upcoming release date?

**Pull request merged**
