### PR TITLE
Ensuring that version is a string as a fix for issue #216

### PR DESCRIPTION
**Pull request by ramirantala**
This should fix the issue #216 

Version is set "" instead of None when version has no value.

### CODE REVIEW

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
@ramirantala could you please rebase so zappr run again and we can merge?

**Comment by prayerslayer** [comment]
I didn't deploy the fix for this yet, so for now you have to disable zappr temporarily 😭

**Comment by prayerslayer** [comment]
Retriggering a run of Zappr now...

**Comment by rafaelcaricio** [comment]
@prayerslayer thank you! 👍

**Pull request merged**
