### PR TITLE
Ability to place a stack into maintenance mode #443

### PR DESCRIPTION
**Pull request by imduffy15**
Given a stack it will detect all asgs within that stack negates the tag named 'maintenance' and do the same on all instances currently belonging to that asg.

$ senza maintenance some-stack-name
Changing maintenance mode on Auto Scaling Group some-stack-name-version-AppServer-1R2KFL5HLI5NT..
Maintance mode set to False for some-stack-name-version-AppServer-1R2KFL5HLI5NT

$ senza maintenance some-stack-name
Changing maintenance mode on Auto Scaling Group some-stack-name-version-AppServer-1R2KFL5HLI5NT..
Maintance mode set to True for some-stack-name-version-AppServer-1R2KFL5HLI5NT

Signed-off-by: Ian Duffy <ian.duffy@zalando.ie>

### CODE REVIEW

**Comment by hjacobs** [comment]
Hmm, I'm not sure if this feature makes sense to have in Senza directly. It sounds very special and application specific (some app needs to actually interpret the AWS tag).

It also breaks Cloud Formation update handling as tags are directly manipulated via the AWS API.

**Comment by imduffy15** [comment]
> Hmm, I'm not sure if this feature makes sense to have in Senza directly

Thought this might be the case alright. Didn't see any better place to put it other than a team specific script but that required a bit of re-work to get the base thats already in senza.

> it sounds very special and application specific

The idea would be to have the ZMON checks looking for the maintenance tag.

> It also breaks Cloud Formation update handling as tags are directly manipulated via the AWS API.

As does patch :)

**Comment by hjacobs** [comment]
@imduffy15 I'm not totally opposed, but I would at least like to see others supporting (and using) your idea. It probably makes no sense to have this code in Senza for only one user.

The command is not idempotent as it toggles the flag, this might be dangerous when used in scripts (?).

**Comment by imduffy15** [comment]
> The command is not idempotent as it toggles the flag, this might be dangerous when used in scripts (?).

Okay, I'll add a parameter for on/off.

**Comment by imduffy15** [comment]
Discussed in zmon chat with @Jan-M  he suggested using https://docs.zmon.io/en/latest/user/downtimes.html however that will not work for entities that do not yet exist.

**Comment by hjacobs** [comment]
I'm closing this as it got no support from other users and I don't want to merge something specifically for one (or a few) users only.

**Pull request closed without merging**
